# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_section_section_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='direct_data',
            field=models.CharField(default='null', max_length=1500),
        ),
    ]
